### ISSUE TITLE
Incorrect phrase / use of the language

### ISSUE THREAD

**Issue by witchlane** [learn-co-curriculum/dsc-correlation-covariance#1]
I have an idea of what is attempted to be stated here but it came out really poorly.  This sentence needs to be corrected - see underlined part in image below.
![image](https://user-images.githubusercontent.com/44211854/52515943-7e24d800-2bf0-11e9-9414-e5254891a793.png)

**Comment by LoreDirick** [comment]
@witchlane thanks, solved it!
